### ISSUE TITLE
1.0.0 Release Work

### ISSUE THREAD

**Issue by lamchakchan** [xogroup/bunnybus#2]
#### Context

This is an issue tracker to help as a high level checklist for items needing to be accomplished.

## TODO
- [x] Setup build for Travis CI or CircleCI
  - [x] Need docker build support to handle `rabbitmq` image
- [x] Load Test
  - [x] using `callback`
  - [x] using `Promise`
- [x] grep all `TODO` in code base and fix.
- [x] adding `Promise` returns object when `callback` is not provided
- [x] API documentation
  - [x] TOC listing
  - [x] Core API Documentation with Callback
  - [x] Core API Documentation with Promise
- [x] CONTRIB documentation
- [x] TEST documentation
- [x] API support for `rabbit-killswitch` support
  - [x] exposing the subscription state management
- [x] Logging support
  - [x] inherit `EventEmitter` interface on to BunnyBus
    - [x] create events for `log.info`, `log.error`, `log.fatal`, `log.warn`, `log.debug`
    - [x] create log interface adapter for above events when a log contract is provided through log configuration.
    - [x] define log contract + log configuration
 - [ ] Optimization
   - [x] Optimize for caching in Connection
   - [x] Optimize for caching in Channel
   - [x] Optimize for caching in Exchange
   - [x] Optimize for caching in Queue

**Comment by lamchakchan** [comment]
Complete!
